
!###############################################################################

!-------------------------------------------------------------------------------
! The Roslin Institute, The University of Edinburgh - AlphaGenes Group
!-------------------------------------------------------------------------------
!
!> @file     CompatibilityModule.f90
!
! DESCRIPTION:
!> @brief    Module cotaining subroutines to deal with text PLINK format
!> @details  currently only contains integer and real heap sort procedures 
!
!> @author   David Wilson, david.wilson@roslin.ed.ac.uk
!
!> @date     January 4, 2017
!
!> @version  1.0.0
!
!
!-------------------------------------------------------------------------------






function readToPedigreeFormat(pedFile) result(ped)
    use ConstantModule, only : IDLENGTH
    use AlphaHouseMod, only : countLines
    use PedigreeModule

    type(pedigreeHolder) :: ped !< Pedigree object that is returned
    character(len=*), intent(in) :: pedFile !< .ped file generated by plink
    character(len=IDLENGTH) :: familyID,gender,phenotype
    integer :: fileUnit,stat, i,lines
    character(len=IDLENGTH),dimension(:,:), allocatable :: pedArray
    integer, allocatable, dimension(:) :: genderArray, phenotypeArray

    lines=  countLines(pedFile)
   
    allocate(pedArray(3,lines))
    allocate(genderArray(lines))
    allocate(phenotypeArray(lines))                
    
    open(newUnit=fileUnit, file=pedFile, status="old")
    do i=1, lines
        read(fileUnit,*) familyID,pedArray(1,i),pedArray(2,i),pedArray(3,i),gender,phenotype

        read(gender,*,iostat=stat)  genderArray(i)
        read(phenotype,*,iostat=stat)  phenotypeArray(i)
    enddo


    ped = PedigreeHolder(pedArray, genderArray)



end function readToPedigreeFormat
